### ISSUE TITLE
Wallet app doesn't open a second time with encrypted wallet

### ISSUE THREAD

**Issue by bradkendall** [kittycash/wallet#105]

**Comment by bradkendall** [comment]
@evanlinjin 

# Replication Steps

**Start wallet:**
`go run ${GOPATH}/src/github.com/kittycash/wallet/cmd/wallet/wallet.go \
--cxo-address="127.0.0.1:6140" \
--http-address="127.0.0.1:6148" \
--messenger-addresses=":8880"`

**Create an encrypted wallet:**

`curl -X POST \
  http://127.0.0.1:6148/api/wallets/new \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 3c903527-424d-4fa1-a8ab-2097be0bccd9' \
  -d 'label=crash_wallet&seed=secure%20seed&aCount=1&encrypted=true&password=securepass'`

**Kill the wallet:**

`pkill wallet`

**Restart the wallet:**

`go run ${GOPATH}/src/github.com/kittycash/wallet/cmd/wallet/wallet.go \
--cxo-address="127.0.0.1:6140" \
--http-address="127.0.0.1:6148" \
--messenger-addresses=":8880"`


# Error output from wallet

```INFO[0000] no blockchain yet                             error="no such head"
INFO[0000] finished preparing blockchain                
INFO[0000] closing blockchain manager                   
INFO[0000] closed CXO chain DB                          
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder.(*decoder).dchk(0xc4200fb7f8, 0x149ade0, 0xc42001f110, 0x198, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:813 +0x1045
github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder.(*decoder).dchk(0xc4200fb7f8, 0x1500480, 0xc42001f100, 0x199, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:801 +0x731
github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder.(*decoder).dchk(0xc4200fb7f8, 0x14fc740, 0xc42001f100, 0x199, 0x6e)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:801 +0x731
github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder.DeserializeRaw(0xc420071650, 0x6e, 0x6e, 0x14bd240, 0xc42001f100, 0x20, 0xc4200fb918)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:169 +0x1b5
github.com/kittycash/wallet/src/wallet.LoadFloatingWallet(0x15cf6e0, 0xc42000e0d8, 0xc420344b63, 0xc, 0x0, 0x0, 0x0, 0xc4200fba20, 0x108f17a)
	/Users/bkendall/go/src/github.com/kittycash/wallet/src/wallet/wallet.go:138 +0x19e
github.com/kittycash/wallet/src/wallet.(*Manager).Refresh.func1(0x15cf6e0, 0xc42000e0d8, 0xc420344b63, 0xc, 0xc420344bc0, 0x33, 0x0, 0x2de9e7e54c704008)
	/Users/bkendall/go/src/github.com/kittycash/wallet/src/wallet/manager.go:50 +0x1ee
github.com/kittycash/wallet/src/wallet.RangeLabels(0xc4200fbb18, 0x0, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/src/wallet/file.go:86 +0x268
github.com/kittycash/wallet/src/wallet.(*Manager).Refresh(0xc4202252f0, 0x0, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/src/wallet/manager.go:40 +0xd4
github.com/kittycash/wallet/src/wallet.NewManager(0xc420024210, 0x22, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/src/wallet/manager.go:27 +0x40
main.action(0xc420020160, 0x0, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/cmd/wallet/wallet.go:260 +0x789
github.com/kittycash/wallet/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x14c5860, 0x1591a68, 0xc420020160, 0xc420081740, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/gopkg.in/urfave/cli.v1/app.go:488 +0x101
github.com/kittycash/wallet/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4202481a0, 0xc4200a80c0, 0x4, 0x4, 0x0, 0x0)
	/Users/bkendall/go/src/github.com/kittycash/wallet/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
	/Users/bkendall/go/src/github.com/kittycash/wallet/cmd/wallet/wallet.go:300 +0x55
exit status 2```
